export const yutAssets = {
  board: '/omok/assets/yut/board/yut-board-master.png',
  yutReference: '/omok/assets/yut/yut/yut-sticks-reference.png',
  specialTilesReference: '/omok/assets/yut/ui/special-tiles-reference.png',
  cardMaster: '/omok/assets/yut/cards/luck-cards-18-master.png',
  cards: {
    plus_one: '/omok/assets/yut/cards/01-plus-one.png',
    plus_two: '/omok/assets/yut/cards/02-plus-two.png',
    minus_one: '/omok/assets/yut/cards/03-minus-one.png',
    opponent_back: '/omok/assets/yut/cards/04-opponent-back.png',
    reroll: '/omok/assets/yut/cards/05-reroll.png',
    shield: '/omok/assets/yut/cards/06-shield.png',
    merge: '/omok/assets/yut/cards/07-merge.png',
    split: '/omok/assets/yut/cards/08-split-opponent.png',
    extra_turn: '/omok/assets/yut/cards/09-extra-turn.png',
    nothing: '/omok/assets/yut/cards/10-nothing.png',
    plus_four: '/omok/assets/yut/cards/11-plus-four.png',
    teleport: '/omok/assets/yut/cards/12-teleport.png',
    golden_yut: '/omok/assets/yut/cards/13-golden-yut.png',
    last_place_boost: '/omok/assets/yut/cards/14-last-place-boost.png',
    swap: '/omok/assets/yut/cards/15-swap.png',
    minus_three: '/omok/assets/yut/cards/16-minus-three.png',
    forced_split: '/omok/assets/yut/cards/17-forced-split.png',
    chaos_swap: '/omok/assets/yut/cards/18-chaos-swap.png',
  },
  ui: {
    gameUiReference: '/omok/assets/yut/ui/game-ui-reference.png',
    eventBadges: '/omok/assets/yut/ui/event-badges.png',
    turnAndRollButtons: '/omok/assets/yut/ui/turn-and-roll-buttons.png',
    titleAndYutBag: '/omok/assets/yut/ui/title-and-yut-bag.png',
  },
} as const
